### ISSUE TITLE
The .json file in the get_corpus.py code was not found

### ISSUE THREAD

**Issue by qiuyue97** [Richard88888/KD-CGEC#1]
The '/data0/xp/gec/ChineseNMT/data/json/train_nlpcc.json' file cannot be found in the links provided for the three datasets by the author.

**Comment by richard-peng-xia** [comment]
I apologize for my mistake. Since the project has been over for a long time, my server account and data have been deleted. Perhaps you can refer to other similar CGEC projects e.g., [MuCGEC](https://github.com/HillZhang1999/MuCGEC) and [NLPCC 2018 official data set](http://tcci.ccf.org.cn/conference/2018/dldoc/trainingdata02.tar.gz) to organize this data into the desired format. Good luck :)

**Comment by qiuyue97** [comment]
Thank you for the response, I will try using the similar projects you provided.
